"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getUserHome = exports.rimrafPromify = exports.copyFiles = exports.errorCapture = exports.hasMultipleCores = exports.hasYarn = exports.mergeConfig = exports.parallelToSerial = exports.spinner = exports.loadEnv = exports.updateNotifier = exports.semverGt = exports.logger = exports.findProcess = exports.which = exports.clipboardy = exports.address = exports.inquirer = exports.cliui = exports.rimraf = exports.execa = exports.chalk = exports.deepmerge = exports.open = exports.fs = void 0;
var fs_extra_1 = __importDefault(require("fs-extra"));
exports.fs = fs_extra_1.default;
var open_1 = __importDefault(require("open"));
exports.open = open_1.default;
var deepmerge_1 = __importDefault(require("deepmerge"));
exports.deepmerge = deepmerge_1.default;
var chalk_1 = __importDefault(require("chalk"));
exports.chalk = chalk_1.default;
var execa_1 = __importDefault(require("execa"));
exports.execa = execa_1.default;
var rimraf_1 = __importDefault(require("rimraf"));
exports.rimraf = rimraf_1.default;
var cliui_1 = __importDefault(require("cliui"));
exports.cliui = cliui_1.default;
var inquirer_1 = __importDefault(require("inquirer"));
exports.inquirer = inquirer_1.default;
var address_1 = __importDefault(require("address"));
exports.address = address_1.default;
var clipboardy_1 = __importDefault(require("clipboardy"));
exports.clipboardy = clipboardy_1.default;
var which_1 = __importDefault(require("which"));
exports.which = which_1.default;
var find_process_1 = __importDefault(require("find-process"));
exports.findProcess = find_process_1.default;
var gt_1 = __importDefault(require("semver/functions/gt"));
exports.semverGt = gt_1.default;
var logger_1 = __importDefault(require("./src/logger"));
exports.logger = logger_1.default;
var updateNotifier_1 = __importDefault(require("./src/updateNotifier"));
exports.updateNotifier = updateNotifier_1.default;
var loadEnv_1 = __importDefault(require("./src/loadEnv"));
exports.loadEnv = loadEnv_1.default;
var spinner = __importStar(require("./src/spinner"));
exports.spinner = spinner;
var parallelToSerial_1 = __importDefault(require("./src/parallelToSerial"));
exports.parallelToSerial = parallelToSerial_1.default;
var mergeConfig_1 = __importDefault(require("./src/mergeConfig"));
exports.mergeConfig = mergeConfig_1.default;
var hasYarn_1 = __importDefault(require("./src/hasYarn"));
exports.hasYarn = hasYarn_1.default;
var hasMultipleCores_1 = __importDefault(require("./src/hasMultipleCores"));
exports.hasMultipleCores = hasMultipleCores_1.default;
var errorCapture_1 = __importDefault(require("./src/errorCapture"));
exports.errorCapture = errorCapture_1.default;
var copyFiles_1 = __importDefault(require("./src/copyFiles"));
exports.copyFiles = copyFiles_1.default;
var rimrafPromify_1 = __importDefault(require("./src/rimrafPromify"));
exports.rimrafPromify = rimrafPromify_1.default;
var getUserHome_1 = __importDefault(require("./src/getUserHome"));
exports.getUserHome = getUserHome_1.default;
